linters-settings:
  goimports:
    local-prefixes: github.com/ruko1202/balun.courses-microservice-6stream/api-gateway
  gosec:
    excludes:
      - G505 # sha1
      - G401 # sha1

linters:
  disable-all: true
  enable:
    - revive
    - gocritic
    - stylecheck
    - goimports
    - gosec
    - unconvert
    - unparam
    - errcheck
    - gosimple
    - ineffassign
    - unused

issues:
  exclude:
    - 'returns unexported type'
    - 'WriteFile permissions to be 0600 or less'
  exclude-dirs:
    - ./pkg/*

run:
  timeout: 10m
