services:
  nginx:
    image: nginx
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - "80:80"
    depends_on:
      - api-gateway
      - auth
      - chat-message
      - friend
      - media
      - notification
      - user-profile

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: .build/Dockerfile
      args:
        - SERVICE_NAME=api-gateway

  auth:
    build:
      context: ./auth
      dockerfile: .build/Dockerfile
      args:
        - SERVICE_NAME=auth

  chat-message:
    build:
      context: ./chat-message
      dockerfile: .build/Dockerfile
      args:
        - SERVICE_NAME=chat-message

  friend:
    build:
      context: ./friend
      dockerfile: .build/Dockerfile
      args:
        - SERVICE_NAME=friend

  media:
    build:
      context: ./media
      dockerfile: .build/Dockerfile
      args:
        - SERVICE_NAME=media

  notification:
    build:
      context: ./notification
      dockerfile: .build/Dockerfile
      args:
        - SERVICE_NAME=notification

  user-profile:
    build:
      context: ./user-profile
      dockerfile: .build/Dockerfile
      args:
        - SERVICE_NAME=user-profile
