// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: template_service2/template_service2.proto

package template_service2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ping          string                 `protobuf:"bytes,1,opt,name=ping,proto3" json:"ping,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_template_service2_template_service2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_template_service2_template_service2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_template_service2_template_service2_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetPing() string {
	if x != nil {
		return x.Ping
	}
	return ""
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pong          string                 `protobuf:"bytes,1,opt,name=pong,proto3" json:"pong,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_template_service2_template_service2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_template_service2_template_service2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_template_service2_template_service2_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetPong() string {
	if x != nil {
		return x.Pong
	}
	return ""
}

func (x *PingResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_template_service2_template_service2_proto protoreflect.FileDescriptor

const file_template_service2_template_service2_proto_rawDesc = "" +
	"\n" +
	")template_service2/template_service2.proto\x12\x11template_service2\x1a\x1fgoogle/protobuf/timestamp.proto\"!\n" +
	"\vPingRequest\x12\x12\n" +
	"\x04ping\x18\x01 \x01(\tR\x04ping\"\\\n" +
	"\fPingResponse\x12\x12\n" +
	"\x04pong\x18\x01 \x01(\tR\x04pong\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp2U\n" +
	"\bService2\x12I\n" +
	"\x04Ping\x12\x1e.template_service2.PingRequest\x1a\x1f.template_service2.PingResponse\"\x00B\xc6\x01\n" +
	"\x15com.template_service2B\x15TemplateService2ProtoP\x01Z6github.com/bufbuild/buf-examples/gen/template_service2\xa2\x02\x03TXX\xaa\x02\x10TemplateService2\xca\x02\x10TemplateService2\xe2\x02\x1cTemplateService2\\GPBMetadata\xea\x02\x10TemplateService2b\x06proto3"

var (
	file_template_service2_template_service2_proto_rawDescOnce sync.Once
	file_template_service2_template_service2_proto_rawDescData []byte
)

func file_template_service2_template_service2_proto_rawDescGZIP() []byte {
	file_template_service2_template_service2_proto_rawDescOnce.Do(func() {
		file_template_service2_template_service2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_template_service2_template_service2_proto_rawDesc), len(file_template_service2_template_service2_proto_rawDesc)))
	})
	return file_template_service2_template_service2_proto_rawDescData
}

var file_template_service2_template_service2_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_template_service2_template_service2_proto_goTypes = []any{
	(*PingRequest)(nil),           // 0: template_service2.PingRequest
	(*PingResponse)(nil),          // 1: template_service2.PingResponse
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_template_service2_template_service2_proto_depIdxs = []int32{
	2, // 0: template_service2.PingResponse.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: template_service2.Service2.Ping:input_type -> template_service2.PingRequest
	1, // 2: template_service2.Service2.Ping:output_type -> template_service2.PingResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_template_service2_template_service2_proto_init() }
func file_template_service2_template_service2_proto_init() {
	if File_template_service2_template_service2_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_template_service2_template_service2_proto_rawDesc), len(file_template_service2_template_service2_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_template_service2_template_service2_proto_goTypes,
		DependencyIndexes: file_template_service2_template_service2_proto_depIdxs,
		MessageInfos:      file_template_service2_template_service2_proto_msgTypes,
	}.Build()
	File_template_service2_template_service2_proto = out.File
	file_template_service2_template_service2_proto_goTypes = nil
	file_template_service2_template_service2_proto_depIdxs = nil
}
