# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy

project_name: template-service

builds:
  - id: "main"
    env:
      - GOAMD64=""
      - CGO_ENABLED=0
    no_unique_dist_dir: true
    main: ./cmd/service
    binary: "{{ .ProjectName }}_{{ .Target }}"
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/ruko1202/balun.courses-microservice-6stream/internal/config/build.appName={{.ProjectName}}
      - -X github.com/ruko1202/balun.courses-microservice-6stream/internal/config/build.version={{.Version}}
      - -X github.com/ruko1202/balun.courses-microservice-6stream/internal/config/build.os={{.Version}}
      - -X github.com/ruko1202/balun.courses-microservice-6stream/internal/config/build.arch={{.Version}}
      - -X github.com/ruko1202/balun.courses-microservice-6stream/internal/config/build.buildTime={{.Version}}
      - -X github.com/ruko1202/balun.courses-microservice-6stream/internal/config/build.shaCommit={{.Version}}

gitlab_urls:
  # set to true if you want to upload to the Package Registry rather than attachments
  # Only works with GitLab 13.5+
  use_package_registry: true

  # Set this if you set GITLAB_TOKEN to the value of CI_JOB_TOKEN.
  use_job_token: true

archives:
  - formats: [ binary ]
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

snapshot:
  # Allows you to change the name of the generated snapshot
  #
  # Note that some pipes require this to be semantic version compliant (nfpm,
  # for example).
  #
  # Default: `{{ .Version }}-SNAPSHOT-{{.ShortCommit}}`.
  # Templates: allowed.
  version_template: "{{ .Tag }}-{{ .ShortCommit }}"
